import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Aviões na Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1 className={styles.title}>
          Aviões na Web
        </h1>
      </header>

      <main className={styles.main}>

        <p className={styles.description}>
          Crie rankings e comparativos entre aviões
        </p>

        <div className={styles.wrap}>
          <div className={`${styles.float} ${styles.center}`}>
            <h2 className={styles.textCenter}>Ranking</h2>
            <ul className={styles.list}>
              <li>Mais rápidos</li>
              <li>Mais lentos</li>
              <li>Mais pesados</li>
              <li>Mais leves</li>
              <li>Mais curtos</li>
              <li>Mais longos</li>
              <li>Mais novos</li>
              <li>Mais antigos</li>
            </ul>
          </div>
          <div className={`${styles.float} ${styles.center}`}>
            <h2 className={styles.textCenter}>Comparativo</h2>
            <label>Avião A: <input className={styles.input} id='planeA' /></label>
            <br />
            <label>Avião B: <input className={styles.input} id='planeB' /></label>
            <button className={styles.mainButton}>Ir</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>Feito com 💚 por Brenno Calado</a>
      </footer>
    </div>
  )
}

export default Home
