import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Aviões na Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1 className={styles.title}>
          Aviões na Web
        </h1>
      </header>

      <main className={styles.main}>

        <p className={styles.description}>
          Crie rankings e comparativos entre aviões
        </p>

        <div className={styles.wrap}>
          <div className={`${styles.float} ${styles.center}`}>
            <h2 className={styles.textCenter}>Ranking</h2>
            <ul className={styles.list}>
              <li><Link href="/ranking-fastest">Mais rápidos</Link></li>
              <li><Link href="/ranking-slowest">Mais lentos</Link></li>
              <li><Link href="/ranking-heaviest">Mais pesados</Link></li>
              <li><Link href="/ranking-lightest">Mais leves</Link></li>
              <li><Link href="/ranking-shortest">Mais curtos</Link></li>
              <li><Link href="/ranking-longest">Mais longos</Link></li>
              <li><Link href="/ranking-newest">Mais novos</Link></li>
              <li><Link href="/ranking-oldest">Mais antigos</Link></li>
            </ul>
          </div>
          <div className={`${styles.float} ${styles.center}`}>
            <h2 className={styles.textCenter}>Comparativo</h2>
            <label>Avião A: <input className={styles.input} id='planeA' /></label>
            <br />
            <label>Avião B: <input className={styles.input} id='planeB' /></label>
            <button className={styles.mainButton}>Ir</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/brenno-calado">Feito com 💚 por Brenno Calado</a>
      </footer>
    </div>
  )
}

export default Home
